### ISSUE TITLE
Tensorflow_datasets package not working as expected. 

### ISSUE THREAD

**Issue by sophwats** [thoth-station/s2i-tensorflow-gpu-notebook#3]
**Describe the bug**
When using the tensorflow notebook image on RHODS, tensorflow_datasets package doesn't behave as expected. 

Expected behaviour: loads the data set as shown here: https://www.tensorflow.org/datasets/overview#tfdsload
Actual behavior: `AttributeError: module 'tensorflow_datasets' has no attribute 'load'`

![Screen Shot 2021-05-24 at 12 25 12 PM](https://user-images.githubusercontent.com/5311289/119384990-1c86bb80-bc8b-11eb-98c3-c7575e9d17fa.png)

Please see screenshot to see the error. 

The code works as expected in google colab.

**Comment by harshad16** [comment]
The package tensorflow_datasets, isnt present directly in the image.
install this by default.
